# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-01-31 12:26:48
"""
import arcpy
from sys import argv

def Model(Buffer_radius="500 Meters", Camera_trap_map_points_="Sampling sites\\Sampling sites: camera traps", Water_surface_polygon_="Environmental covariate_ layers\\GTA Waterbodies 2019", Green_areas_polygons_="Environmental covariate_ layers\\Parks and Recreational areas", Tree_canopy_cover_shapefile_="Environmental covariate_ layers\\TOPO_TREED_AREA_WGS84", Built_impervious_surface_area_shapefile_="Environmental covariate_ layers\\Builtarea", Digital_Elevation_model_raster_="Environmental covariate_ layers\\SouthernOntarioDigitalElevationModel2002.tif", NDVI_index_raster_="Environmental covariate_ layers\\NDVI Vegetation index 30m res.", Population_density_raster_="Environmental covariate_ layers\\GHS_POP_E2015_GLOBE_R2019A_54009_250_V1_0_11_3.tif", Output="C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Sampling_sites_bufferareas", Statistics_Mean_or_Median="MEDIAN", Transfer_Fields=["MEDIAN"]):  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\users\tizge\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\GeoAnalytics Desktop Tools.tbx")
    arcpy.ImportToolbox(r"c:\users\tizge\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\Analysis Tools.tbx")

    # Process: Buffer (Buffer) (analysis)
    Full_buffers = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Sampling_sites_bufferareas"
    arcpy.analysis.Buffer(in_features=Camera_trap_map_points_, out_feature_class=Full_buffers, buffer_distance_or_field=Buffer_radius, line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

    # Process: Overlay Layers 1 (Overlay Layers) (gapro)
    non_flooded_buffers = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Samplingsites__buffer_NoWaterSurface"
    arcpy.gapro.OverlayLayers(input_layer=Full_buffers, overlay_layer=Water_surface_polygon_, out_feature_class=non_flooded_buffers, overlay_type="ERASE")

    # Process: Summarize Within 1 (Summarize Within) (analysis)
    Tree = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Tree250"
    TreeTable = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\TreeTable250"
    arcpy.analysis.SummarizeWithin(in_polygons=non_flooded_buffers, in_sum_features=Tree_canopy_cover_shapefile_, out_feature_class=Tree, keep_all_polygons="KEEP_ALL", sum_fields=[], sum_shape="ADD_SHAPE_SUM", shape_unit="SQUAREKILOMETERS", group_field="subtype", add_min_maj="NO_MIN_MAJ", add_group_percent="ADD_PERCENT", out_group_table=TreeTable)

    # Process: Add Join 1 (Add Join) (management)
    Tree_points = arcpy.management.AddJoin(in_layer_or_view=Tree, in_field="Join_ID", join_table=TreeTable, join_field="Join_ID", join_type="KEEP_ALL")[0]

    # Process: Join Field 1 (Join Field) (management)
    Buffers_1 = arcpy.management.JoinField(in_data=Full_buffers, in_field="Name", join_table=Tree_points, join_field="Name", fields=["TreeTable250.PercentArea"])[0]

    # Process: Summarize Within 2 (Summarize Within) (analysis)
    Built = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Samplingsite_builtarea2_250fix"
    BuiltTable = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\builtarea_summary250fix"
    arcpy.analysis.SummarizeWithin(in_polygons=non_flooded_buffers, in_sum_features=Built_impervious_surface_area_shapefile_, out_feature_class=Built, keep_all_polygons="KEEP_ALL", sum_fields=[], sum_shape="ADD_SHAPE_SUM", shape_unit="SQUAREKILOMETERS", group_field="gridcode", add_min_maj="NO_MIN_MAJ", add_group_percent="ADD_PERCENT", out_group_table=BuiltTable)

    # Process: Add Join 2 (Add Join) (management)
    Built_points = arcpy.management.AddJoin(in_layer_or_view=Built, in_field="Join_ID", join_table=BuiltTable, join_field="Join_ID", join_type="KEEP_ALL")[0]

    # Process: Join Field 2 (Join Field) (management)
    Buffers_2 = arcpy.management.JoinField(in_data=Buffers_1, in_field="Name", join_table=Built_points, join_field="Name", fields=["builtarea_summary250fix.PercentArea"])[0]

    # Process: Zonal Statistics as Table 1 (Zonal Statistics as Table) (sa)
    DEM = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\DEM"
    arcpy.sa.ZonalStatisticsAsTable(in_zone_data=non_flooded_buffers, zone_field="Name", in_value_raster=Digital_Elevation_model_raster_, out_table=DEM, ignore_nodata="DATA", statistics_type=Statistics_Mean_or_Median, process_as_multidimensional="CURRENT_SLICE", percentile_values=90, percentile_interpolation_type="AUTO_DETECT")
    .save(Zonal_Statistics_as_Table_1)


    # Process: Join Field 3 (Join Field) (management)
    Buffers_3 = arcpy.management.JoinField(in_data=Buffers_2, in_field="Name", join_table=DEM, join_field="Name", fields=Transfer_Fields)[0]

    # Process: Zonal Statistics as Table 2 (Zonal Statistics as Table) (sa)
    NDVI = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\NDVI"
    arcpy.sa.ZonalStatisticsAsTable(in_zone_data=non_flooded_buffers, zone_field="Name", in_value_raster=NDVI_index_raster_, out_table=NDVI, ignore_nodata="DATA", statistics_type=Statistics_Mean_or_Median, process_as_multidimensional="CURRENT_SLICE", percentile_values=90, percentile_interpolation_type="AUTO_DETECT")
    .save(Zonal_Statistics_as_Table_2)


    # Process: Join Field 4 (Join Field) (management)
    Buffers_4 = arcpy.management.JoinField(in_data=Buffers_3, in_field="Name", join_table=NDVI, join_field="Name", fields=Transfer_Fields)[0]

    # Process: Overlay Layers 2 (Overlay Layers) (gapro)
    non_green_buffers = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\Samplingsites_buffers_NoGreenSurface"
    arcpy.gapro.OverlayLayers(input_layer=non_flooded_buffers, overlay_layer=Green_areas_polygons_, out_feature_class=non_green_buffers, overlay_type="ERASE")

    # Process: Zonal Statistics as Table 3 (Zonal Statistics as Table) (sa)
    POP = "C:\\Users\\tizge\\Documents\\ArcGIS\\Map Camera traps\\Default.gdb\\POP"
    arcpy.sa.ZonalStatisticsAsTable(in_zone_data=non_green_buffers, zone_field="Name", in_value_raster=Population_density_raster_, out_table=POP, ignore_nodata="DATA", statistics_type=Statistics_Mean_or_Median, process_as_multidimensional="CURRENT_SLICE", percentile_values=[90], percentile_interpolation_type="AUTO_DETECT")
    .save(Zonal_Statistics_as_Table_3)


    # Process: Join Field 5 (Join Field) (management)
    Output = arcpy.management.JoinField(in_data=Buffers_4, in_field="Name", join_table=POP, join_field="Name", fields=Transfer_Fields)[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\tizge\Documents\ArcGIS\Map Camera traps\Default.gdb", workspace=r"C:\Users\tizge\Documents\ArcGIS\Map Camera traps\Default.gdb"):
        Model(*argv[1:])
